# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 2%

# Package-specific flags
flags:
  core:
    paths:
      - packages/core/src/
    carryforward: true

  react-hook-form:
    paths:
      - packages/react-hook-form/src/
    carryforward: true

# Comment settings
comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore paths
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.config.*"
  - "**/dist/**"
  - "**/node_modules/**"
  - "**/__tests__/**"
  - "**/locales/**"
  - "apps/demo/**"
